on:
  pull_request:
jobs:
  build_apptainer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v2
        with:
          just-version: '1.4.0'
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.3
      - name: build the apptainer
        run: just build
